# Generated by Django 4.2.2 on 2023-07-01 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='forum.thread'),
            preserve_default=False,
        ),
    ]
