# Generated by Django 4.2.2 on 2023-07-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_thread_posts_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new',
            field=models.CharField(default='1', max_length=1),
            preserve_default=False,
        ),
    ]
