# Generated by Django 4.2.2 on 2023-07-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='new',
        ),
    ]
